// eslint-disable-next-line import/prefer-default-export
export const mockProductData = {
	id: 100000000000001,
	slug: "bounce-running-shoe",
	sku: "bounce-running-shoe",
	description:
		"From weekend warriors to elite athletes, the Bounce Running Shoe is a cutting-edge evolution in running shoe technology. A snug, yet flexible knit upper hugs your foot. While our patented Bouncetech foam provides world class support and comfort. All of this riding on an organic rubber outsole that delivers an incredibly grippy ride beneath your feet.",
	name: "Bounce Running Shoe",
	type: "Physical",
	onHand: null,
	taxCode: null,
	hasVariant: false,
	variantConfig: null,
	parentVariant: null,
	childVariants: [],
	pricing: [
		{
			currencyCode: "USD",
			currencyDisplayFormat: "symbol",
			currencyLocale: "en-US",
			schema: {},
			prices: [
				{
					type: "List",
					amount: "116.00",
				},
				{
					type: "Sale",
					amount: "95.00",
				},
			],
		},
	],
	schema: {
		featuredImage: {
			label: "Featured Image",
			value: [
				{
					_id: "VKZHWND37FEQZEVPKVF5UB5ZLA",
					auth: { 1: "9b58a8aa066ce58413f2578968082f00bc44fdfa9b20ed674de2d94f193da93c" },
					created_date: "2022-08-29T21:07:37Z",
					height: 2500,
					image_type: "photograph",
					last_updated_date: "2022-08-29T21:07:37Z",
					licensable: false,
					owner: { id: "sandbox.arccommerce", sponsored: false },
					subtitle: "Bounce Running Shoe - Blue Heather",
					type: "image",
					url: "https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.arccommerce/VKZHWND37FEQZEVPKVF5UB5ZLA.jpg",
					version: "0.10.3",
					width: 2500,
				},
			],
		},
		productGallery: {
			label: "Gallery",
			value: [
				{
					_id: "QG5BUKLJGVGERAQPYL56MLSQ3Q",
					auth: { 1: "22d0edb9ff3661f1697ddccca84c7fe03e14ae19f6535f83b738b003de448594" },
					created_date: "2022-08-29T21:07:37Z",
					credits: { affiliation: [] },
					height: 2500,
					image_type: "photograph",
					last_updated_date: "2022-08-29T21:07:37Z",
					licensable: false,
					owner: { id: "sandbox.arccommerce", sponsored: false },
					subtitle: "Bounce Running Shoe - Blue Heather",
					type: "image",
					url: "https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.arccommerce/QG5BUKLJGVGERAQPYL56MLSQ3Q.jpg",
					version: "0.10.3",
					width: 2500,
				},
				{
					_id: "YRSQBVMJ5JBONNYLF7TVZB4A34",
					auth: { 1: "240c4421292379e0026708f5fe63726294442220ec4c8b0186e09e07ab044a1f" },
					created_date: "2022-08-29T21:07:37Z",
					credits: { affiliation: [] },
					height: 2500,
					image_type: "photograph",
					last_updated_date: "2022-08-29T21:07:37Z",
					licensable: false,
					owner: { id: "sandbox.arccommerce", sponsored: false },
					subtitle: "Bounce Running Shoe - Blue Heather",
					taxonomy: { associated_tasks: [] },
					type: "image",
					url: "https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.arccommerce/YRSQBVMJ5JBONNYLF7TVZB4A34.jpg",
					version: "0.10.3",
					width: 2500,
				},
				{
					_id: "RAQ7K6CYZZD6DCCDMKR37R6WJU",
					auth: { 1: "020853b4adff8f46201f5b64066b2aac59f71ef892a68409703a309cd7f43823" },
					created_date: "2022-08-29T21:07:37Z",
					credits: { affiliation: [] },
					height: 2500,
					image_type: "photograph",
					last_updated_date: "2022-08-29T21:07:37Z",
					licensable: false,
					owner: { id: "sandbox.arccommerce", sponsored: false },
					subtitle: "Bounce Running Shoe - Blue Heather",
					type: "image",
					url: "https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.arccommerce/RAQ7K6CYZZD6DCCDMKR37R6WJU.jpg",
					version: "0.10.3",
					width: 2500,
				},
				{
					_id: "3C7XFYBTT5D6THV4LIM2WFFFHM",
					auth: { 1: "71854a0dba31ce5f271418d553dd8248f967c3cdf4c09c97eff1b7131d6058d3" },
					created_date: "2022-08-29T21:07:37Z",
					credits: { affiliation: [] },
					height: 2500,
					image_type: "photograph",
					last_updated_date: "2022-08-29T21:07:37Z",
					licensable: false,
					owner: { id: "sandbox.arccommerce", sponsored: false },
					subtitle: "Bounce Running Shoe - Blue Heather",
					taxonomy: { associated_tasks: [] },
					type: "image",
					url: "https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.arccommerce/3C7XFYBTT5D6THV4LIM2WFFFHM.jpg",
					version: "0.10.3",
					width: 2500,
				},
			],
		},
		productDetails: {
			label: "Product Details",
			value:
				"<p>Indigo produced it first running shoe over 35 years ago, and since then, the Bounce Running Shoe is the favored training shoe for all categories of runners. From those just beginning their journey to Olympic medalists, the Bounce Running shoe provides the comfort, durability, and performance that make pushing your boundaries a daily possibility. The Bounce Running Shoe incorporates cutting-edge materials combined with classic contours that make your running journey a dream.</p><ul><li>Bespoke knit upper</li><li>Bouncetech foam midsole</li><li>Organic rubber outsole</li><li>Made in the U.S.A.</li></ul>",
			dataType: "string",
			visible: true,
			configuration: null,
		},
		sizeAndFit: {
			label: "Size & Fit",
			value:
				"<p>The Bounce Running Shoe is available in the following U.S. men’s shoe sizes</p><ul><li>7</li><li>8</li><li>9</li><li>10</li><li>11</li><li>12</li><li>13</li></ul>",
			dataType: "string",
			visible: true,
			configuration: null,
		},
		shippingAndReturns: {
			label: "Shipping & Returns",
			value:
				"<p>Free standard shipping and free 30-day returns on all items purchased from Indigo. <a href=''>Learn More</a></p>",
			dataType: "string",
			visible: true,
			configuration: null,
		},
	},
};
