export default (site) => ({
	resizerURL: 'https://corecomponents-the-prophet-prod.cdn.arcpublishing.com/resizer',
	websiteDomain: '',
	websiteName: '',
	facebookPage: true,
	twitterUsername: true,
	rssUrl: true,
	copyrightText: true,
	lightBackgroundLogo: 'https://arcdesignsystem.com/img/arc-logo-black.svg',
	lightBackgroundLogoAlt: 'light logo alt text',
	primaryLogo: 'https://www.klartale.no/img/klartale/klartale-logo-new.svg',
	primaryLogoAlt: 'primary logo alt text',
	fallbackImage: 'https://cloudfront-us-east-1.images.arcpublishing.com/corecomponents/4PUA6PJWEBEELOHMHMUUUB2WSM.JPG',
	dateLocalization: {
		language: 'en',
		timeZone: 'America/New_York',
		dateTimeFormat: "LLLL d, yyyy 'at' K:m bbbb z",
		dateFormat: 'LLLL d, yyyy',
	},
});
