// eslint-disable-next-line import/prefer-default-export
export const headerNavMock = [
	{
		_id: "link-WAZKB2KXTT0QZ76P4C5ZK1A7VM",
		children: [],
		display_name: "Latest News",
		node_type: "link",
		url: "/latest/",
	},
	{
		_id: "link-PH5KKEVJAD63D9M9329ZPWAX94",
		children: [],
		display_name: "Shoes",
		node_type: "link",
		url: "/shoes",
	},
	{
		_id: "/business-technology",
		children: [],
		name: "Business & Technology",
		node_type: "section",
	},
	{
		_id: "/news",
		children: [
			{
				_id: "/news/politics",
				name: "Politics",
				node_type: "section",
			},
			{
				_id: "/local",
				name: "Local",
				node_type: "section",
			},
			{
				_id: "/news/business",
				name: "Business",
				node_type: "section",
			},
			{
				_id: "/news/world",
				name: "World",
				node_type: "section",
			},
		],
		name: "News",
		node_type: "section",
	},
	{
		_id: "/sports",
		children: [],
		name: "Sports",
		node_type: "section",
	},
	{
		_id: "/arts",
		children: [],
		name: "Arts",
		node_type: "section",
	},
	{
		_id: "link-36CW7DJXD96Z5E5UC3FC9C8KMR",
		children: [],
		display_name: "Digital Subscription",
		node_type: "link",
		url: "https://subscribe.washingtonpost.com/acquisition/?&tid=s_006&promo=o6",
	},
	{
		_id: "/footer-titles/contact-us",
		children: [],
		name: "Contact Us",
		node_type: "section",
	},
	{
		_id: "/footer-titles/about-us",
		children: [
			{
				_id: "link-B3WGXB4C8T64B4K2RZX84H9Y7M",
				display_name: "Privacy Policy",
				node_type: "link",
				url: "https://www.washingtonpost.com/policies-and-standards/",
			},
			{
				_id: "link-YPU9HTTH3563V3T5092Z7JMM5M",
				display_name: "Terms of Service",
				node_type: "link",
				url: "https://www.washingtonpost.com/terms-of-service/2011/11/18/gIQAldiYiN_story.html",
			},
			{
				_id: "link-GJ0FX8B7FN4NN0AQ736T84MP08",
				display_name: "Submissions and Discussion Policy",
				node_type: "link",
				url: "https://www.washingtonpost.com/news/ask-the-post/discussion-and-submission-guidelines/",
			},
			{
				_id: "link-VHVEPZTW6X6A5A5EW2A0AZQYNM",
				display_name: "Policies and Standards",
				node_type: "link",
				url: "https://www.washingtonpost.com/policies-and-standards/",
			},
			{
				_id: "link-7GBNGM0C5D3BV6EN1R7Y821MZR",
				display_name: "Home Delivery",
				node_type: "link",
				url: "https://subscribe.washingtonpost.com/acquisition/?oscode=RPW5&tid=s_005&promo=o18",
			},
			{
				_id: "link-Q7B54P8FU10CQ85RE61BNNGVV8",
				display_name: "Newsletters & Alerts",
				node_type: "link",
				url: "https://subscribe.washingtonpost.com/newsletters",
			},
			{
				_id: "link-R4Y4171RGN1QDBPX4BX8XAF4HM",
				display_name: "Help",
				node_type: "link",
				url: "https://helpcenter.washingtonpost.com/hc/en-us",
			},
			{
				_id: "link-2GERBTKG2519K237E6ZQZMKR3R",
				display_name: "Mobile & Apps",
				node_type: "link",
				url: "/wp-srv/contents/mobile/",
			},
			{
				_id: "link-TJ1N041VUH0CK8725DPUKX776W",
				display_name: "Advertise",
				node_type: "link",
				url: "/advertise",
			},
			{
				_id: "link-JB2QY6P8M537X7NF64CTU10CAG",
				display_name: "Ad Choices",
				node_type: "link",
				url: "https://www.washingtonpost.com/how-can-i-opt-out-of-online-advertising-cookies/2011/11/18/gIQABECbiN_story.html",
			},
			{
				_id: "link-VACCJ72KPD1X77ZY6B7YTRWRV4",
				display_name: "Gift Subscriptions",
				node_type: "link",
				url: "https://subscribe.washingtonpost.com/gift?promo=g_d",
			},
			{
				_id: "link-6CM6NDQK4T0ANFZEU7377Q752G",
				display_name: "Events",
				node_type: "link",
				url: "/blogs/post-live/",
			},
			{
				_id: "link-TNC4ATKCF92838DT3VHBTDGFG0",
				display_name: "Reprints & Permissions",
				node_type: "link",
				url: "https://www.washingtonpostreprints.com/",
			},
			{
				_id: "link-5NF6N79ZM52FTEQP0WV39CHX3W",
				display_name: "In the Community",
				node_type: "link",
				url: "https://www.washingtonpost.com/community",
			},
			{
				_id: "link-KC5YFPCC4H25997QRWCETH2D3G",
				display_name: "RSS Terms of Service",
				node_type: "link",
				url: "https://www.washingtonpost.com/rss-terms-of-service/2012/01/16/gIQAadFYAQ_story.html",
			},
		],
		name: "About Us",
		node_type: "section",
	},
	{
		_id: "link-8EJXY04HJ533H9WDAU31ZNZR3R",
		children: [],
		display_name: "Contact",
		node_type: "link",
		url: "https://helpcenter.washingtonpost.com/hc/en-us/requests/new",
	},
	{
		_id: "/footer-titles/terms-of-use",
		children: [],
		name: "Terms of Use",
		node_type: "section",
	},
	{
		_id: "/sponsored",
		children: [],
		name: "Sponsored",
		node_type: "section",
	},
	{
		_id: "/sponsored/starbucks",
		children: [],
		name: "Starbucks",
		node_type: "section",
	},
	{
		_id: "link-7Q8D9JZ16D65B3WYP158BEMHJM",
		children: [],
		display_name: "Contact Us",
		node_type: "link",
		url: "/contact-us",
	},
	{
		_id: "link-JKZ61DCTHT1AXEFFCXMFMQWAT4",
		children: [],
		display_name: "Careers",
		node_type: "link",
		url: "http://washingtonpostmedia.com/careers",
	},
	{
		_id: "link-8QFADJTQHT52KD7436CQJRVYJ4",
		children: [],
		display_name: "Post Store",
		node_type: "link",
		url: "https://www.washingtonpost.com/store/",
	},
	{
		_id: "/test/promo-image-variations",
		children: [],
		name: "Promo image variations",
		node_type: "section",
	},
	{
		_id: "link-6Y5DDWQTDH1PQFDZAQWZN0K560",
		children: [],
		display_name: "News Service & Syndicate",
		node_type: "link",
		url: "http://syndication.washingtonpost.com/",
	},
	{
		_id: "link-0HNCDNRVMX54Q74RCCBQJX3PM8",
		children: [],
		display_name: "Reader Representative",
		node_type: "link",
		url: "mailto:readers@washpost.com",
	},
	{
		_id: "link-ZGGMMAQQC15B16VQ18RY7T20QR",
		children: [],
		display_name: "BrandStudio",
		node_type: "link",
		url: "https://www.washingtonpost.com/sf/brand-connect/brand-studio/",
	},
];
