#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# this only for targeting canary at the moment 
# fetching latest changes to ensure the origin/canary is up to date
git fetch -a --depth 100 && npm run lint:changed-feature-branch && npm run test:changed-feature-branch