#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# fetching latest changes to ensure the origin/arc-themes-release-version-1.20 is up to date
# git fetch -a --depth 100 && npm run lint:changed-feature-branch && npm run test:changed-feature-branch
