name: Beta blocks publish to beta tag
on:
  push:
    branches:
      - beta
    # only run on changes to these files
    paths:
      - "**.js"
      - "**.jsx"
      - "**.scss"
      - "**/intl.json"
      - "**/README.md"

# Publishes beta builds with the dist tag of "beta" and
jobs:
  publish:
    name: Beta block publish
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Set git username
        run: git config --global user.email "jack.howard@washpost.com" && git config --global user.name "Jack Howard"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.NODE_AUTH_TOKEN }}

      # pulls all tags (needed for lerna / semantic release to correctly version)
      - name: Pull tags to give lerna access to git info
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Clean install (CI) dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Run tests
        run: npm run test

      - name: Publish to beta
        run: npm run release:beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Check beta failure status
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
