# .github/workflows/generate-intl-files.yml

name: Generate intl json block files

on:
  push:
    branches:
      - "lokalise*"
    paths:
      - locale/*.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create npmrc
        env:
          ARCXP_AUTH_TOKEN: ${{ secrets.WPMEDIA_PUBLIC_REPO_ARCXP_PACKAGE_TOKEN }}
        run: |
          touch .npmrc
          echo @wpmedia:registry=https://npm.pkg.github.com/ >> .npmrc
          echo @arcxp:registry=https://npm.pkg.github.com/ >> .npmrc
          echo //npm.pkg.github.com/:_authToken=$ARCXP_AUTH_TOKEN >> .npmrc

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Clean install (CI) dependencies if lockfile (above) changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Generate intl
        run: npm run generate:intl

      # Add and commit the changed files
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "Add block intl.json files"
