name: Stable blocks publish to stable tag
on:
  push:
    branches:
      - stable
    # only run on changes to these files
    paths:
      - "**.js"
      - "**.jsx"
      - "**.scss"
      - "**/intl.json"
      - "**/README.md"

# Publishes stable builds with the dist tag of "stable" and
jobs:
  publish:
    name: Stable block publish
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # pulls all tags (needed for lerna / semantic release to correctly version)
      - name: Pull tags to give lerna access to git info
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean install (CI) dependencies if lockfile (above) changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: npm run test

      # iterates minor version
      - name: Publish to stable
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          npm run release:stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check stable failure status
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
