name: Test Blocks And Linting - Changed from main

on:
  pull_request:
    # synchronize	commit(s) pushed to the pull request
    types: [synchronize, opened]
    branches:
      - main

jobs:
  ensure_minimum_test_coverage_linting:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          #  0 indicates all history for all branches and tags
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Clean install (CI) dependencies if lockfile (above) changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests on changed since main
        run: npm run test:changed-feature-branch

      - name: Check linting of changed since main
        run: npm run lint:changed-feature-branch

      - name: Check failure status
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
